### ISSUE TITLE
Unittest framework

### ISSUE THREAD

**Issue by marekmosna** [eteran/c-vector#22] opened 2022-01-14 20:41 UTC
What do you think to involve any unit testing framework like catch2, gtest, ...
It's really helpful and it doesn't provide such a printf battle and even all CIs support such a approach. For instance GitHub Actions can do a great job for you

**Comment by andy5995** [comment] 2022-01-14 21:06
Hi @marekmosna ,

What do you mean by "printf battle"?

**Comment by marekmosna** [comment] 2022-01-14 22:21
Print to the output inside the test shouldn't be. Unit test frameworks provide you standardized output based on testing values. You can after decide if you want to abort the test or continue and just fire up the message, it depends.

**Comment by eteran** [comment] 2022-01-15 03:46
@marekmosna I'm in favor of having a nice unit test framework, as well as tests which exercise and stress test specific parts of the code! I can say that overall, since this is a single header project, I'd like whatever framework that is used to be as light weight as possible.

Honestly, in the past, I've often used a series of target executables which runs tests and assert on failure that are just driven with cmake's built in ability to run tests with a `make tests`. But I'm open to sometime more "official" too so long as it's not too heavy :-)

**Comment by marekmosna** [comment] 2022-01-15 22:07
[Catch2](https://github.com/catchorg/Catch2) is for instance headers only testing framework. I'm used to integrate it as an [External project](https://cmake.org/cmake/help/latest/module/ExternalProject.html). It's couple of lines in the `CMakeLists.txt` and rest is job for the cmake invocation. It's pretty useful.

**Comment by marekmosna** [comment] 2022-01-18 18:51
I was thinking a bit about your requirement @eteran and the most important is the comfort of writing the tests. It isn't involved in production so it doesn't matter how much memory or compile time does it take. I've got experiences with `boost`, `catch2` and `gtest` and they do the great job.

**Comment by eteran** [comment] 2022-01-18 18:57
@marekmosna Undersood, and I agree. It's more of a guideline than a requirement since "too heavy" is also a matter of taste :-). 

Any one of those frameworks would certainly do the trick. 

Unrelated, but I asked on the other PR, how come you closed it? It was planning on merging sometime this week if you still wanted to get it in.

**Comment by marekmosna** [comment] 2022-01-18 19:03
I had to work on it to be able to integrate it so, now there is much more changes than just added `cvector_reserve`. I can again make just this simple one for you.

**Comment by marekmosna** [comment] 2022-01-18 19:15
Check [my fork](https://github.com/genesissoftware-tech/c-vector) and if you will be interested in any feature I made, just let me know.

**Comment by marekmosna** [comment] 2022-01-18 19:17
Now I'm planning to involve the unit test framework but another situation comes up.  According to the issue this can solved first on your repo and I can just update mine

**Comment by eteran** [comment] 2022-02-02 04:23
@marekmosna I like your fork! I actually just updated the repo to have a .clang-format that reflects my style (but uses spaces!).

But also I think that your fork has a flaw in the `assert` and `malloc` related features. Basically, your code unconditionally uses `cvector_malloc` (and related), but that macro is only defined if `CVECTOR_CUSTOM_MALLOC` is specified. This effectively **requires** that `CVECTOR_CUSTOM_MALLOC` be set to even use the library.

I've fixed this in my repo in that `cvector_malloc` is defined if not already defined by the user, which i think is what we really want here. We want it to default to using `malloc` and family, but be overridable should the user want it. There's a similar concern for the custom `assert` stuff you've done.

So I'm certainly intersted in more PRs :-) Especially involving the unit test stuff you spoke about.

That being said, I'm not a fan of the `BEGIN_BLOCK` / `END_BLOCK` stuff as I think, for me, it's an unessary abstraction for such a small header only library.

Either way, thanks for the contributions!

**Comment by marekmosna** [comment] 2022-02-04 17:09
And what about [doctest](https://github.com/doctest/doctest)?

**Comment by eteran** [comment] 2022-02-04 21:42
Seems simple enough to work with, I like it's simplicity!

**Comment by marekmosna** [comment] 2022-02-05 21:03
Are you gonna integrate any by yourself? There is a bunch of possibilities how to make it and I don't like be in position where I didn't read mind properly and the way I made it is just "not liked".

**Comment by eteran** [comment] 2022-02-05 22:53
Glad you asked because I was assuming you'd just make a PR. But now that I understand your preference, I can spend some time next week on it making some unit-tests for this. Shouldn't take took long because it's a pretty simple library.

**Comment by marekmosna** [comment] 2022-02-06 00:22
> Glad you asked because I was assuming you'd just make a PR. But now that I understand your preference, I can spend some time next week on it making some unit-tests for this. Shouldn't take took long because it's a pretty simple library.

Thank you @eteran. Please do what you can. It's yours repo. I can adapt to anything you'll make. The way is not important for me, the result is. When you integrate the framework I can rewrite some tests for you.

**Comment by marekmosna** [comment] 2022-03-20 20:19
Hi @eteran 

How are you doing? Are you gonna integrate any framework? I was forced to leave your implementation due to lack of tests. In case you won't, please close this issue.

Thanks 
Marek

**Comment by eteran** [comment] 2022-03-20 20:27
I'm doing alright. Have been unfortunately very busy in personal life recently, but definitely do plan to get a test framework in there soon.

It's just been a bit hectic. I hope to get it done soon 🙂

**Comment by eteran** [comment] 2022-03-22 18:56
@marekmosna OK, so I've done some digging into unit test stuff and... it's harder than one might think because this codebase is C.

While I can technically use something like catch2 or doctest, but because they are C++ specific, that would require adding a whole bunch of casts between `void*` and the somehow detected target pointer type. Basically, `int *p = malloc(4)` is legal C, but not legal C++.

So, I'm looking for a framework that lets me write the tests in C, and **almost** found one that seemed good. (cester), which unfortunately seems to throw false positives on it's automagical memory leak detection (confirmed with valgrind, there is no leak) :-/. 

So I think that one is a non-starter.

So I guess one question is, do it have to be a framework? What if we just used cmake's ctest capabilities natively? Where each test is it's own source file with a main, and just asserts what must be true? And we'd run the tests with just like `make test` or `ctest`

Sure, it would be nice if the tests could be all in one file for such a small library, but I don't see many great options for unit testing C code that "just work".

Thoughts?

**Comment by eteran** [comment] 2022-03-22 19:22
@marekmosna (sorry for the rapid messages if they are a bother).

OK, so I've added some unit tests! They are based on the main test code, but actually do exercise most of the code pretty well as far as I can tell.

You can run them with any of:

```
make && make test
```

```
make check
```

or if you'd like to see the per-test output: 

```
make
./unit-tests
```

I hope this works for your needs :-)

I'll be closing this issue, but do feel free to re-open if I messed something up, or open another issue if there is other stuff that you feel is needed.

Thanks!

**Closed by eteran** 2022-03-22 19:22 UTC
